const colors = require('tailwindcss/colors')
const spacer = 1;
module.exports = {
    purge:{
        enabled:false,
    },
    corePlugins: [
        'backgroundColor',
        'textColor',
        'borderColor',
        'transitionProperty',
        'transitionDuration',
        'transitionTimingFunction',
        'transitionDelay',
        'fontSize',
        'fontStyle',
        'fontWeight',
        'textAlign',
        'letterSpacing',
        'display',
        'flexDirection',
        'flexWrap',
        'gridTemplateColumns',
        'gridColumnStart',
        'gridTemplateRows',
        'gridRow',
        'gridAutoFlow',
        'gridAutoColumns',
        'gridAutoRows',
        'gap',
        'width',
        'borderRadius',
        'padding',
        'margin',
        'boxShadow',
        'appearance',
        'verticalAlign',
        'outline',
        'inset',
        'transform',
        'rotate',
        'opacity',
        'scale',
        'translate'
    ],
    darkMode: false,
    theme: {
        extend:{},
        colors: {
            //transparent: 'transparent',
            //current: 'currentColor',
            teal:colors.teal,
            green:colors.green,
            purple:colors.purple,
            //orange:colors.orange,
            //black: colors.black,
            //white: colors.white,
            gray: colors.coolGray,
            //red: colors.red,
            //yellow: colors.amber,
            blue: colors.blue,
            //pink: colors.pink,
        },
        spacing: {
            1: (spacer * .25)+'rem',
            2: (spacer * .5)+'rem',
            3: (spacer * .75)+'rem',
            4: spacer+'rem',
            5: (spacer * 1.25)+'rem',
            6: (spacer * 1.5)+'rem',
            7: (spacer * 1.75)+'rem',
            8: (spacer * 2)+'rem',
            9: (spacer * 2.25)+'rem',
            10: (spacer * 2.5)+'rem',
            11: (spacer * 2.75)+'rem',
            12: (spacer * 3)+'rem',
            13: (spacer * 3.25)+'rem',
            14: (spacer * 3.5)+'rem',
            15: (spacer * 3.75)+'rem',
            16: (spacer * 4)+'rem',
            17: (spacer * 4.25)+'rem',
            18: (spacer * 4.50)+'rem',
            19: (spacer * 4.75)+'rem',
            20: (spacer * 5)+'rem',
        },
    },
}